image: Ubuntu2204
stack: node 20
branches:
  only:
    - main
cache: node_modules
install:
  - yarn install
build: off
build_script:
  - yarn run build
test_script:
  - yarn run lint

deploy_script:  
  - git config --global credential.helper store
  - git config --global user.name saetovdinar
  - git config --global user.email saetonskie@mail.ru
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"
