image: Visual Studio 2019
stack: node 22
branches:
  only:
    - main
cache: node_modules
install:
  - yarn install
build: off
build_script:
  - yarn run build
test_script:
  - yarn run lint

deploy_script:  
  - git config --global credential.helper store
  - git config --global user.name saetov98
  - git config --global user.email saetonskie@mail.ru
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose